version: '3'

services:
  casino-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    depends_on:
      - Casino_api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/Casino_api
      - SPRING_DATASOURCE_USERNAME=bob4o-mysql
      - SPRING_DATASOURCE_PASSWORD=1000

  Casino_api:
    image: mysql:latest
    ports:
      - "3306:3306"
      - "15672:15672"
    environment:
      MYSQL_ROOT_PASSWORD: 1000
      MYSQL_DATABASE: Casino_api
    volumes:
      - ./data:/var/lib/mysql
