version: '3'

services:
  casino-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - casino-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/Casino_api

  casino-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1000
      MYSQL_DATABASE: Casino_api
    volumes:
      - ./data:/var/lib/mysql
