spring:
  datasource:
    url: jdbc:mysql://localhost:3306/casinodb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false       # Set to false in production
    database-platform: org.hibernate.dialect.MySQLDialect
