spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Casino_api
    username: bob4o-mysql
    password: 1000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
    port: 4040